---
title: "Final Project"
author: "Lily Monte"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())

library(tidyverse)
library(tidycensus)
library(sf)
library(ggspatial)
library(osmdata)
library(prettymapr)
library(leaflet)
library(nabor)
library(stargazer)
library(units)
library(igraph)

setwd("C:/Users/Lily/Documents/collegefiles/PLAN 372/PLAN372_hmks/final")

#buildings = st_read("north-carolina-latest-free.shp/gis_osm_buildings_a_free_1.shp")
placesarea = st_read("north-carolina-latest-free.shp/gis_osm_places_a_free_1.shp")
placespoints = st_read("north-carolina-latest-free.shp/gis_osm_places_free_1.shp")
blockgroups = st_read("tl_2020_37_bg.shp")
vehicles = st_read("SimplyAnalytics_Shapefiles_0925eb1f4a8a3f21f2436e4e13cc300110faeaefa280d3df2246d9af9fdda95e.shp")
```
```{r}
blockgroups = blockgroups %>% 
  filter(COUNTYFP == "183")
```


```{r}
st_crs(blockgroups)

blockgroups = st_transform(blockgroups, 4326)
vehicles = st_transform(vehicles, 4326)
#ensures all data uses the same EPSG Code

raleigh = filter(placesarea, name == "Raleigh" | name == "Cary" | name == "Garner" | name == "Apex" | name == "Wake County" | name == "Wendell" | name == "Zebulon")

lawoffices = raleigh %>% 
  st_bbox() %>% 
  opq() %>% 
  #add_osm_feature(key = "office", value = "lawyer") %>%
  add_osm_features (features = c (
        "\"office\"=\"lawyer\"",
        "\"amenity\"=\"courthouse\"",
        "\"office\"=\"notary\"",
        "\"government\"=\"administrative\"",
        "\"government\"=\"register_office\"",
        "\"government\"=\"prosecutor\"")) %>% 
  #add_osm_feature(key = "amenity", value = "courthouse") %>% 
  osmdata_sf()
#The above code pulls legal services from the osm database

#highways = raleigh %>% 
  #st_bbox() %>% 
  #opq() %>% 
  #add_osm_features(features = list(
   # "highway" = "motorway",
   # "highway" = "primary",
   # "highway" = "secondary",
   # "highway" = "tertiary"
 # )) %>% 
  #osmdata_sf()

lawoffices

lawofficespoints = bind_rows(
  pluck(lawoffices, "osm_points"),
  st_centroid(pluck(lawoffices, "osm_polygons"))
)
#converts the obtained spatial data into a spataial dataframe

#highwaylines = pluck(highways, "osm_lines")


ggplot()+
  annotation_map_tile(type = "osm", zoomin = 0) +
  geom_sf(data = blockgroups, color = "black", fill = NA)+
  #geom_sf(data = highwaylines, color = "black") +
  geom_sf(data = lawofficespoints, color = "blue") + 
  theme_void() + 
  labs(title = "Fig. 1. Map of Wake County",
       subtitle = "Legal Services and Courthouses in Blue")
#plots blockgroups and legal services.

```
```{r}
buffer = lawofficespoints %>% 
  st_buffer(dist = 3218.69)
#creates a circle around each law office point

access = ggplot() +
    annotation_map_tile(type = "osm", zoomin = 0) +
    geom_sf(data = blockgroups, color = "black", fill = NA) +
    geom_sf(data = buffer, alpha = 0.05, fill = "darkgreen", color = "darkgreen")+
    theme_void() + 
    labs(title = "Fig. 2. Map of Wake County",
       subtitle = "Accessible Areas in Green")
access
#this plots the circles, indicating areas with 2 mile access to a legal service
```
```{r}
join = blockgroups %>% 
  st_join(buffer,
          join = st_intersects,
          left = T) %>% 
  mutate(access = ifelse(is.na(osm_id),"Limited Access", "Good Access")) %>% 
  mutate(access = as.factor(access))
#this joins the buffer and the block groups, then creates a new column for block groups identifying ones which are in any part touched by one of the buffers

Access2 = ggplot() +
  scale_fill_manual(values = c("darkgreen","darkred")) +
  geom_sf(data = join, color = "black",  alpha = 0.5, aes(fill = access))+
  geom_sf(data = lawofficespoints, color = "blue") + 
  theme_void() + 
  labs(title="Fig. 3. Access to Legal Services in Wake County",
       subtitle = "By Census Block Group") +
  annotation_scale(location = "bl", width_hint = 0.3)
  
Access2
#plots the above
```

```{r}
v24 <- load_variables(2023, "acs5", cache = TRUE)
v24 = v24 %>% 
  filter(geography == "block group")

blockgroupcensus = get_acs(geography = "cbg",
        variables = "B19013_001",
        year = 2023,
        state = "NC",
        county = "Wake")
#pulls more variables from the us census, specifically income data


censusblocks = left_join(blockgroups, blockgroupcensus)
#another join, combining this with the previous data

income = ggplot(data = censusblocks, aes(fill = estimate)) +
    #annotation_map_tile(type = "osm", zoomin = 0) +
    geom_sf(color = "black") +
    theme_void() + 
    labs(title = "Fig. 4. Map of Wake County Census Block Groups by Income")
income
#plots each block group by income
```



```{r}
accessjoin = join %>% 
  select(access, GEOID)
accessjoin = st_join(censusblocks, accessjoin)
#joins the census data with data on access

accessjoin = accessjoin %>% 
  mutate(accessdummy = ifelse(access == "Good Access", 1, 0))
#turns the access variable into a numerical dummy variable

fit1 = lm(accessdummy ~ estimate, data = accessjoin)
summary(fit1)
#conducts a linear regression based on the join
plot1 = ggplot()+
  geom_jitter(data = accessjoin, aes(x = estimate, y = accessdummy), height = 0.1)
plot1

stargazer(fit1)

vehiclesjoin = st_join(accessjoin, vehicles)

fit2 = lm(accessdummy ~ VALUE1, data = vehiclesjoin)
summary(fit2)
#more linear regressions 


```



```{r}
blockgroupcentroids = st_centroid(blockgroups)
#calculating the centroid of each block group

ggplot() +
  geom_sf(data = blockgroupcentroids, color = "black")


blockgroupcentroids$type = "blockgroup"
lawofficespoints$type = "lawoffice"

blockgroupcentroids = blockgroupcentroids %>%
  mutate(nodeID = c(1:n()))

lawofficespoints = lawofficespoints %>%
  mutate(nodeID = c(1:n()))
#gives each node a unique id

nearestindices = st_nearest_feature(blockgroupcentroids, lawofficespoints)

nearest_points = lawofficespoints[nearestindices, ]

nearest_distances <- st_distance(blockgroupcentroids, nearest_points, by_element = TRUE)
nearest_distances_mi = set_units(nearest_distances, "mi")

distanceresults = cbind(
  #st_drop_geometry(blockgroupcentroids), # Drop the geometry to avoid duplication
  nearest_point_id = lawofficespoints$id[nearestindices],
  nearest_x = st_coordinates(nearest_points)[, 1],
  nearest_y = st_coordinates(nearest_points)[, 2],
  nearest_distances_mi = nearest_distances_mi,
  geometry = blockgroupcentroids$geometry
)

distanceresults = as.data.frame(distanceresults)
#this all calculates the distance between each centroid and its nearest legal service

nearestdf = distanceresults %>% 
  select(nearest_x, nearest_y)

nearestdf = st_as_sf(distanceresults, coords = c("nearest_x", "nearest_y"), crs = 4326)

distanceresults = st_as_sf(distanceresults, crs = 4326)

censuscentroids = st_centroid(censusblocks)

censuscentroids = left_join(censuscentroids, as.data.frame(distanceresults))

max(as.numeric(censuscentroids$nearest_distances_mi))
min(as.numeric(censuscentroids$nearest_distances_mi))


```


```{r}
ggplot(data = censuscentroids, aes(x = estimate, y = as.numeric(nearest_distances_mi)))+
  geom_point() + 
  labs(title = "Fig. 5. Distribution of Groups by Income Against Distance from Closest Legal Service",
       x = "Estimated Median Income",
       y = "Distance to Closest Legal Service (Mi)") +
  geom_smooth(method = "lm")

fit3 = lm(as.numeric(nearest_distances_mi) ~ estimate, data = censuscentroids)
summary(fit3)
stargazer(fit3)
#creates another linear model out of the distances

vehiclecentroids = st_centroid(vehicles)
#calculates the centroid of the vehicles dataframe

totalcentroids = left_join(censuscentroids, as.data.frame(vehiclecentroids), by = join_by(GEOID == spatial_id))
#joins all the centroid geometries into one that has every variable included

totalcentroids = totalcentroids %>% 
  mutate(vehicleprop = VALUE1/VALUE0)

ggplot(data = totalcentroids, aes(x = vehicleprop, y = as.numeric(nearest_distances_mi))) +
  geom_point() + 
  labs(title = "Fig. 6",
       x = "Proportion of Households without a Vehicle",
       y = "Distance to Nearest Legal Service") +
  geom_smooth(method = "lm")

fit4 = lm(as.numeric(nearest_distances_mi)~vehicleprop, data = totalcentroids)
summary(fit4)
stargazer(fit4)

```


```{r}
centroid_coords <- st_coordinates(blockgroupcentroids)
law_coords <- st_coordinates(lawofficespoints)
#this takes the coordinates of the block group centroids and the law office points for use with nabor
nn_result <- nabor::knn(law_coords, centroid_coords, k = 1)
#

lines_list <- lapply(seq_len(nrow(centroid_coords)), function(i) {
  st_linestring(rbind(centroid_coords[i, ], law_coords[nn_result$nn.idx[i], ]))
})

lines_sf <- st_sf(
  geometry = st_sfc(lines_list, crs = st_crs(blockgroupcentroids)),
  from_id = seq_len(nrow(blockgroupcentroids)),
  to_id = nn_result$nn.idx[,1]
)

#This code to turn the points into a network of lines is taken from stackexchange user Spacedman

edges <- data.frame(
  from = paste0("block_", lines_sf$from_id),
  to = paste0("law_", lines_sf$to_id)
)
#this makes a dataframe with ids for network analysis
centralitygraph <- graph_from_data_frame(edges, directed = FALSE)
#this converts from df to graph data

deg_centrality <- degree(centralitygraph, mode = "all")
#this calculates degree centrality

lawoffice_nodes <- names(deg_centrality)[grepl("^law_", names(deg_centrality))]
#this is a step which is not necessary but probably good practice, naming each of the nodes

law_ids <- as.integer(gsub("law_", "", lawoffice_nodes))

centrality_df <- data.frame(
  law_id = law_ids,
  degree = deg_centrality[lawoffice_nodes]
)

lawofficespoints$degree_centrality <- centrality_df$degree[match(seq_len(nrow(lawofficespoints)), centrality_df$law_id)]
lawofficespoints$degree_centrality <- as.numeric(lawofficespoints$degree_centrality)
lawofficespoints$degree_centrality[is.na(lawofficespoints$degree_centrality)] <- 0
#all of this code puts degree centrality as a column into the lawofficespoints df

ggplot() +
  geom_sf(data = blockgroups, color = "black", fill = NA) +
  geom_sf(data = lawofficespoints, aes(color = degree_centrality, size = degree_centrality)) +
  scale_color_viridis_c(option = "plasma", name = "Degree Centrality") +
  theme_minimal() +
  labs(
    title = "Fig. 8. Law Office Degree Centrality",
    subtitle = "Based on nearest block group connections") +
  annotation_scale(location="bl", width_hint = 0.3) +
  theme_void()
#plotting degree centrality


ggplot() + 
  geom_sf(data = blockgroups, color = "black", fill = NA) +
  #geom_sf(data = distanceresults, color = "black") +
  geom_sf(data = lines_sf, color = "red") +
  geom_sf(data = nearestdf, color = "blue") +
  theme_void() +
  labs(title = "Fig. 7. Legal Services and the Counties they Serve",
       subtitle = "As Determined by Proximity") +
  annotation_scale(location = "bl", width_hint = 0.3)
#plotting connections between law offices and centroids
  

```
